# To execute this docker-compose.yml file use "docker-compose up -d"

#selenium-hub: equivalent to manually running the command "docker run -d -p 4444:4444 --name selenium-hub -P selenium/hub"
selenium-hub:
 restart: always
 image: selenium/hub:latest
 ports:
  - "4444:4444"
#selenium-chrome: equivalent to manually running the command "docker run -d --link selenium-hub:hub -P --name chrome selenium/node-chrome-debug" 
selenium-chrome: 
 restart: always
 image: selenium/node-chrome-debug:latest
 stdin_open: true
 links:
  - selenium-hub:hub
 ports:
  - "5555:5900"
#selenium-firefox: equivalent to manually running the command "docker run -d --link selenium-hub:hub -P --name firefox selenium/node-firefox-debug"
selenium-firefox:
 restart: always
 image: selenium/node-firefox-debug:latest
 links:
  - selenium-hub:hub
 ports:
  - "6666:5900"